version: '3.2'
services:
  bbb-exporter:
    container_name: "visio-monitoring"
    image: cdg47/visio-monitoring:latest
    ports:
    - "127.0.0.1:4000:5000"
    environment:
    - "API_BASE_URL=https://visio.cdg47.fr/bigbluebutton/api/"  # example: https://bbb.example.com/bigbluebutton/api/"
    #- "DEBUG=true"
    env_file:
    # Within this file (secrets.env) which needs to be located in the same directory
    # as docker-compose.yaml, you should have the following line
    # API_SECRET=<TODO: YOUR API SECRET KEY>
    - secrets.env

    restart: unless-stopped
